---
name: ShellCheck

on:
  push:
    paths:
      - '**.sh'
      - '**.bash'
  pull_request:
    paths:
      - '**.sh'
      - '**.bash'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          format: tty
          path: "."
